### ISSUE TITLE
0.18.1 Crash with NeoForge 20.5.0-beta

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nolij/Zume#12]
<s>Crash log.</s> _(Deleted)_

_Works fine under 1.20.5 with Fabric._

**Comment by Nolij** [comment]
Will be fixed by https://github.com/Nolij/Zume/commit/a3e9cd6c58595f5d21df0187ed6c23682ce3a0ea when released.

**Comment by Nolij** [comment]
> @Nolij
> 
> It looks like NeoForge has merged some breaking changes again. Zume [0.19.0-dev.5](https://github.com/Nolij/Zume/releases/tag/release%2F0.19.0-dev.5) crashes again with NeoForge 20.5.16-beta.
> 
> Crash log: https://gist.github.com/3gf8jv4dv/70900dec8c5a596d1fe934c15e780828

I'm convinced embeddedt is paying the NeoForge team to troll me /s

https://github.com/Nolij/Zume/commit/d2d74c4ecacf51e4d60341cb62141fa761938cfe

A dev build containing this fix should be available shortly.

**Comment by Nolij** [comment]
Should be fixed in 0.19.0 now.
