### ISSUE TITLE
Embeddium Options Screen Integration

### ISSUE THREAD

**Issue by Nolij** [Nolij/Zume#16]

**Comment by seriousfreezing** [comment]
It could also be integrated with Sodium (perhaps also with Angelica?). Since in the new versions Sodium already has a version for NeoForge too.

**Comment by Nolij** [comment]
> It could also be integrated with Sodium (perhaps also with Angelica?). Since in the new versions Sodium already has a version for NeoForge too.

Sodium: No for several reasons (logical OR; all of these must change for me to consider it):
1. Sodium provides no (official) options screen API, which means I would need to use a third-party library or mixins to make it work. I don't want to do either of those
2. Sodium is not OSS, and given past interactions with its devs I'd rather not find out what would be their opinion on the legality of either method of interacting with their code.
3. I can't test it without using Sodium, which I don't want to do (see point 4), and I don't (intentionally) ship things I haven't tested.
4. I don't want to support Sodium as a project.

Angelica: I'll consider it when/if they backport the Embeddium options screen API (and to the best of my knowledge they haven't done that yet), but please open a new issue for that when/if it happens.

**Comment by seriousfreezing** [comment]
Okay, fine. But isn't there any other way to have a configuration screen during the game? Like Cloth Config for Fabric users.

**Comment by Nolij** [comment]
> Okay, fine. But isn't there any other way to have a configuration screen during the game? Like Cloth Config for Fabric users.

I'm currently looking at options to have one shared cross-platform config screen. As for Cloth Config, I don't want to go through the effort of configuring every option for several different config screen providers on several different versions. Please join the Discord from the README and send a message in there for further discussion on this topic.
