### ISSUE TITLE
[Neo 20.6] Crash on launch due to incorrect event method signature

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nolij/Zume#22]
I have only tested 1.20.1 and 1.20.6.

- 1.20.1 Lex/Neo/Fabric/Quilt run normally
- 1.20.6 Fabric/Quilt run normally
- 1.20.6 Lex unable to enter the game; 1.20.6 Neo crash when toggle perspectives

[_1.20.6 Lex crash log_](https://gist.github.com/3gf8jv4dv/d7d539f100d745b59b8d457e7b10ede5)
[_1.20.6 Neo crash log_](https://gist.github.com/3gf8jv4dv/db53cce4e130917e43c9995d4d653b55)

**Comment by Nolij** [comment]
20.6+ LexForge is unsupported. I'll fix the 20.6 NeoForge crash though.

**Comment by Nolij** [comment]
Fixed as of [1.0.0-dev.11](https://github.com/Nolij/Zume/releases/tag/release%2F1.0.0-dev.11)
