### ISSUE TITLE
incompatibility with Shoulder Surfing Reloaded mod

### ISSUE THREAD

**Issue by huihiuhuai** [Nolij/Zume#26]
unable to zoom while in shoulder surfing camera mode. mod version 1.7.10.

**Comment by Nolij** [comment]
This issue report does not give me enough information to fix the bug described.

What is "shoulder surfing camera mode"? What mod adds that?

Also, what do you mean by "unable to zoom"? As in it has no effect? Errors? Crash? Weird behaviour?

I would like to resolve this bug but I need more information to do so. Please at the very least provide me reproduction steps, as I'm not aware of a "shoulder surfing camera mode" in any vanilla version of the game, and I have no idea what mod you're using that adds it.

**Comment by huihiuhuai** [comment]
sorry i will provide more information later.

**Comment by Nolij** [comment]
Is [this](https://modrinth.com/mod/kepjj2sy) the mod you're referring to?

**Comment by huihiuhuai** [comment]
[Shoulder Surfing](https://modrinth.com/mod/shoulder-surfing-reloaded). I understand that it has its own keys to adjust the camera but having Zume mod compatibility will still be very beneficial.

**Comment by Nolij** [comment]
Unfortunately, I think this is going to be on them to add compatibility for. They're massively overhauling camera behaviour when shoulder surfing is active. That being said, it should be relatively straightforward for them to add compatibility for Zume using Zume's API. If you are able to get in contact with the dev(s) of that mod please encourage them to reach out to me for guidance on using Zume's API if they need help. Alternatively, they can attempt to just respect the vanilla FOV value, which should at least fix Zume doing nothing while their mod is active.

**Comment by huihiuhuai** [comment]
Zume mod has no effect when you are in the shoulder surfing camera mode. In vanilla camera modes, it works as usual.
