### ISSUE TITLE
Crash the game when entering the graphics settings.

### ISSUE THREAD

**Issue by DragonMotion** [Nolij/Zume#6]
Crash the game when entering the graphics settings.
It happens on version 0.18.0. Everything is fine on version 0.17.0.

oculus-1.6.15a
embeddium-0.3.12
embeddiumplus-v1.2.5
textrues_embeddium_options-0.1.5
zume-0.18.0

https://gist.github.com/DragonMotion/b18189f5581d3344d4dc0bd8050639d2)

**Comment by Nolij** [comment]
This is a bug in Embeddium++. Please wait for Embeddium++ to update, remove Embeddium++, or downgrade Zume to 0.17.0 until then. I'll keep this issue opened but locked to avoid duplicates until that happens.

**Comment by Nolij** [comment]
Fixed in https://github.com/SrRapero720/EmbeddiumPlus/commit/af300cec767c2e752c16893ea816affe9c657f68
